# Generated by Django 4.1.1 on 2022-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='accounts/images/default-avatar.jpeg', upload_to=''),
        ),
    ]
